version: '3.8'

services:
  omni-alpha:
    build: .
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - BOT_BASE_URL=http://localhost:8000
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add Redis for caching (for future features)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    profiles:
      - cache

  # Optional: Add PostgreSQL for data persistence (for future features)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: omni_alpha
      POSTGRES_USER: omni_user
      POSTGRES_PASSWORD: omni_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    profiles:
      - database

volumes:
  redis_data:
  postgres_data:
