version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: omni-postgres
    environment:
      POSTGRES_USER: omni
      POSTGRES_PASSWORD: omni_secure_2024
      POSTGRES_DB: omni_alpha
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=1GB"
      - "-c"
      - "effective_cache_size=3GB"
      - "-c"
      - "maintenance_work_mem=256MB"
      - "-c"
      - "checkpoint_completion_target=0.9"
      - "-c"
      - "wal_buffers=16MB"
      - "-c"
      - "default_statistics_target=100"
      - "-c"
      - "random_page_cost=1.1"
      - "-c"
      - "effective_io_concurrency=200"
      - "-c"
      - "work_mem=5MB"
      - "-c"
      - "min_wal_size=1GB"
      - "-c"
      - "max_wal_size=4GB"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U omni"]
      interval: 10s
      timeout: 5s
      retries: 5

  timescale:
    image: timescale/timescaledb:latest-pg16
    container_name: omni-timescale
    environment:
      POSTGRES_USER: omni
      POSTGRES_PASSWORD: omni_secure_2024
      POSTGRES_DB: market_data
    volumes:
      - timescale_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    command:
      - "postgres"
      - "-c"
      - "max_connections=200"
      - "-c"
      - "shared_buffers=2GB"
      - "-c"
      - "effective_cache_size=6GB"
      - "-c"
      - "timescaledb.max_background_workers=8"
      - "-c"
      - "timescaledb.last_tuned='2024-01-01'"
      - "-c"
      - "timescaledb.last_tuned_version='2.13.0'"

  redis:
    image: redis:7-alpine
    container_name: omni-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command:
      - "redis-server"
      - "--appendonly"
      - "yes"
      - "--maxmemory"
      - "2gb"
      - "--maxmemory-policy"
      - "allkeys-lru"
      - "--tcp-backlog"
      - "511"
      - "--tcp-keepalive"
      - "60"
      - "--timeout"
      - "0"

  mongo:
    image: mongo:7
    container_name: omni-mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: omni
      MONGO_INITDB_ROOT_PASSWORD: omni_secure_2024
      MONGO_INITDB_DATABASE: omni_alpha
    volumes:
      - mongo_data:/data/db
    ports:
      - "27017:27017"

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: omni-redis-commander
    environment:
      REDIS_HOSTS: local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  postgres_data:
  timescale_data:
  redis_data:
  mongo_data:
